name: Release Binaries

on:
  push:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always
  # The name of your Rust crate (should match the name in Cargo.toml)
  CRATE_NAME: pbr

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Build binary
        run: cross build --target ${{ matrix.target }} --release
      - name: Make binary executable
        # UPDATED: Ensure the binary has the executable bit set
        run: chmod +x target/${{ matrix.target }}/release/${{ env.CRATE_NAME }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CRATE_NAME }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.CRATE_NAME }}

  build-macos:
    name: Build macOS Universal Binary
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add required targets
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
      - name: Build for Intel
        run: cargo build --release --target x86_64-apple-darwin
      - name: Build for Apple Silicon
        run: cargo build --release --target aarch64-apple-darwin
      - name: Create Universal Binary
        run: |
          lipo -create -output target/release/${{ env.CRATE_NAME }} \
            target/x86_64-apple-darwin/release/${{ env.CRATE_NAME }} \
            target/aarch64-apple-darwin/release/${{ env.CRATE_NAME }}
      - name: Make binary executable
        # UPDATED: Ensure the universal binary has the executable bit set
        run: chmod +x target/release/${{ env.CRATE_NAME }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CRATE_NAME }}-apple-universal
          path: target/release/${{ env.CRATE_NAME }}

  release:
    name: Create Prerelease
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Package Binaries into Tar Archives
        run: |
          cd artifacts
          for dir in *; do
            tar -czf "$dir.tar.gz" -C "$dir" ${{ env.CRATE_NAME }}
          done
          cd ..

      - name: Create or Update Prerelease with Binaries
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'latest-prerelease'
          name: 'Latest Prerelease'
          body: 'This is a pre-release with the latest binaries from the main branch.'
          prerelease: true
          files: artifacts/*.tar.gz
